package org.bxkr.octodiary.models.userfeed

import org.bxkr.octodiary.models.shared.File

data class Content(
    val attachmentFiles: List<AttachmentFile>?,
    val authorFirstName: String?,
    val authorImageUrl: String?,
    val authorLastName: String?,
    val authorMiddleName: String?,
    val authorName: String?,
    val bannerId: String?,
    val comment: Comment?,
    val commentsCount: Int?,
    val createdDateTime: Int?,
    val date: Int?,
    val endTime: Int?,
    val eventKey: String?,
    val eventSign: String?,
    val eventUrl: String?,
    val externalLink: String?,
    val files: List<File>?,
    val hours: Hours?,
    val id: Long?,
    val imageUrl: String?,
    val internalLink: String?,
    val isNew: Boolean?,
    val isReaded: Boolean?,
    val items: List<Item>?,
    val likes: Any?,
    val linkType: String?,
    val maximumViewsCount: Int?,
    val messengerEntryPoint: Any?,
    val number: Int?,
    val place: Any?,
    val previewUrl: Any?,
    val publicClubId: Any?,
    val startTime: Int?,
    val subject: SubjectX?,
    val subtitle: Any?,
    val text: String?,
    val title: String?,
    val topicEventKey: String?,
    val topicLogoUrl: String?,
    val unsubscribeIsPossible: Boolean?,
    val works: List<Work>?
)