package org.bxkr.octodiary.ui.theme.green

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3B6A1C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBBF294)
val md_theme_light_onPrimaryContainer = Color(0xFF0A2100)
val md_theme_light_secondary = Color(0xFF56624B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD9E7CA)
val md_theme_light_onSecondaryContainer = Color(0xFF141E0C)
val md_theme_light_tertiary = Color(0xFF386665)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBBECEB)
val md_theme_light_onTertiaryContainer = Color(0xFF002020)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFDFDF5)
val md_theme_light_onBackground = Color(0xFF1A1C18)
val md_theme_light_outline = Color(0xFF74796D)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1EA)
val md_theme_light_inverseSurface = Color(0xFF2F312C)
val md_theme_light_inversePrimary = Color(0xFFA0D57B)
val md_theme_light_surfaceTint = Color(0xFF3B6A1C)
val md_theme_light_outlineVariant = Color(0xFFC4C8BB)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFAFAF2)
val md_theme_light_onSurface = Color(0xFF1A1C18)
val md_theme_light_surfaceVariant = Color(0xFFE0E4D6)
val md_theme_light_onSurfaceVariant = Color(0xFF43483E)

val md_theme_dark_primary = Color(0xFFA0D57B)
val md_theme_dark_onPrimary = Color(0xFF163800)
val md_theme_dark_primaryContainer = Color(0xFF245103)
val md_theme_dark_onPrimaryContainer = Color(0xFFBBF294)
val md_theme_dark_secondary = Color(0xFFBDCBAF)
val md_theme_dark_onSecondary = Color(0xFF283420)
val md_theme_dark_secondaryContainer = Color(0xFF3E4A35)
val md_theme_dark_onSecondaryContainer = Color(0xFFD9E7CA)
val md_theme_dark_tertiary = Color(0xFFA0CFCE)
val md_theme_dark_onTertiary = Color(0xFF003737)
val md_theme_dark_tertiaryContainer = Color(0xFF1E4E4E)
val md_theme_dark_onTertiaryContainer = Color(0xFFBBECEB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C18)
val md_theme_dark_onBackground = Color(0xFFE3E3DC)
val md_theme_dark_outline = Color(0xFF8E9286)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C18)
val md_theme_dark_inverseSurface = Color(0xFFE3E3DC)
val md_theme_dark_inversePrimary = Color(0xFF3B6A1C)
val md_theme_dark_surfaceTint = Color(0xFFA0D57B)
val md_theme_dark_outlineVariant = Color(0xFF43483E)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF121410)
val md_theme_dark_onSurface = Color(0xFFC7C7C0)
val md_theme_dark_surfaceVariant = Color(0xFF43483E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C8BB)


val seed = Color(0xFF5F6F52)
